[metadata]
title = "Crab Simulator (2020)"
author = "squarebrackets"
description = "Now for 3DS!"
icons = { ctr = "game/assets/icon.png" }
version = "1.0.0"

[build]
targets = ["ctr"]
source = "game"
packaged = true
